apiVersion: apps/v1

kind: Deployment

metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: backend

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: backend

    spec:
        containers:
          - name: my-backend-container
            image: mmazepa/mybackend
            ports:
              - containerPort: 4000

  replicas: 3
  selector:
    matchLabels:
      type: backend