apiVersion: v1

kind: Service

metadata:
  name: myapp-service

spec:
  type: NodePort
  ports:
    - targetPort: 4000
      port: 4000
      nodePort: 30009

  selector:
    app: myapp
    type: backend
