apiVersion: v1

kind: PersistentVolume

metadata:
  name: postgres-volume

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /c/Users/Mariusz/Tmp/k8s-volume1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - minikube